In [112]:
import pandas as pd

#Cargar el archivo CSV tratado

In [113]:

df = pd.read_csv("datos_tratados/datos_tratados_TelecomXParte2.csv")
df.head()

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total,Cuentas_Diarias
0,0002-ORFBO,0,Female,0,1,1,9,1,No,DSL,...,0,1,1,0,One year,1,Mailed check,65.6,593.30,2.186667
1,0003-MKNFE,0,Male,0,0,0,9,1,Yes,DSL,...,0,0,0,1,Month-to-month,0,Mailed check,59.9,542.40,1.996667
2,0004-TLHLJ,1,Male,0,0,0,4,1,No,Fiber optic,...,1,0,0,0,Month-to-month,1,Electronic check,73.9,280.85,2.463333
3,0011-IGKFF,1,Male,1,1,0,13,1,No,Fiber optic,...,1,0,1,1,Month-to-month,1,Electronic check,98.0,1237.85,3.266667
4,0013-EXCHZ,1,Female,1,1,0,3,1,No,Fiber optic,...,0,1,1,0,Month-to-month,1,Mailed check,83.9,267.40,2.796667

#Verificación rápida: estructura, tipos y nulos

In [114]:
df.shape

(7032, 22)

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   Churn             7032 non-null   int64
 2   gender            7032 non-null   object
 3   SeniorCitizen     7032 non-null   int64
 4   Partner           7032 non-null   int64
 5   Dependents        7032 non-null   int64
 6   tenure            7032 non-null   int64
 7   PhoneService      7032 non-null   int64
 8   MultipleLines     7032 non-null   object
 9   InternetService   7032 non-null   object
 10  OnlineSecurity    7032 non-null   int64
 11  OnlineBackup      7032 non-null   int64
 12  DeviceProtection  7032 non-null   int64
 13  TechSupport       7032 non-null   int64
 14  StreamingTV       7032 non-null   int64
 15  StreamingMovies   7032 non-null   int64
 16  Contract          7032 non-null   object
 17  PaperlessBilling  7032 non-null   int64
 18  PaymentMethod     7032 non-null   object
 19  Charges.Monthly   7032 non-null   float64
 20  Charges.Total     7032 non-null   float64
 21  Cuentas_Diarias   7032 non-null   float64
dtypes: float64(3), int64(13), object(6)
memory usage: 1.2+ MB

In [116]:
# Nulos (top 15)
df.isna().sum().sort_values(ascending=False).head(15)

customerID          0
Churn               0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
dtype: int64

In [117]:
df["Churn"].value_counts()

Churn
0    5163
1    1869
Name: count, dtype: int64

In [118]:
df["Churn"].value_counts(normalize=True) * 100

Churn
0    73.421502
1    26.578498
Name: proportion, dtype: float64

In [119]:
df.columns

Index(['customerID', 'Churn', 'gender', 'SeniorCitizen', 'Partner',
       'Dependents', 'tenure', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod', 'Charges.Monthly', 'Charges.Total',
       'Cuentas_Diarias'],
      dtype='object')

In [120]:
df.dtypes

customerID           object
Churn                 int64
gender               object
SeniorCitizen         int64
Partner               int64
Dependents            int64
tenure                int64
PhoneService          int64
MultipleLines        object
InternetService      object
OnlineSecurity        int64
OnlineBackup          int64
DeviceProtection      int64
TechSupport           int64
StreamingTV           int64
StreamingMovies       int64
Contract             object
PaperlessBilling      int64
PaymentMethod        object
Charges.Monthly     float64
Charges.Total       float64
Cuentas_Diarias     float64
dtype: object

#Eliminación de Columnas Irrelevantes

In [121]:
#Eliminando CustomerID
df_modelo = df.drop(columns=["customerID"])
df_modelo.columns

Index(['Churn', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'Charges.Monthly', 'Charges.Total', 'Cuentas_Diarias'],
      dtype='object')

In [122]:
#Eliminando cuentas_diarias
df_modelo = df_modelo.drop(columns=["Cuentas_Diarias"])
df_modelo.columns

Index(['Churn', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'Charges.Monthly', 'Charges.Total'],
      dtype='object')

In [123]:
#Meto una verificación para estar seguro
print("Columnas finales para modelado:", df_modelo.columns.tolist())
print("¿customerID sigue?", "customerID" in df_modelo.columns)

Columnas finales para modelado: ['Churn', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'Charges.Monthly', 'Charges.Total']
¿customerID sigue? False

#Encoding

In [124]:
#Identificar columnas categóricas y numéricas
X = df_modelo.drop(columns=["Churn"])
y = df_modelo["Churn"]

cat_cols = X.select_dtypes(include=["object"]).columns.tolist()
num_cols = X.select_dtypes(exclude=["object"]).columns.tolist()

print("Categóricas:", cat_cols)
print("Numéricas:", num_cols)

Categóricas: ['gender', 'MultipleLines', 'InternetService', 'Contract', 'PaymentMethod']
Numéricas: ['SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'PaperlessBilling', 'Charges.Monthly', 'Charges.Total']

In [125]:
#Separando train/test antes de codificar
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Train:", X_train.shape, "Test:", X_test.shape)

Train: (5625, 19) Test: (1407, 19)

In [126]:
#Creando el transformador de One-Hot
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

preprocess = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols)
    ],
    remainder="passthrough"  # deja las numéricas tal cual
)

In [127]:
#Aplicando la codificación (fit en train, transform en test)
X_train_enc = preprocess.fit_transform(X_train)
X_test_enc = preprocess.transform(X_test)

print("X_train_enc:", X_train_enc.shape)
print("X_test_enc:", X_test_enc.shape)

X_train_enc: (5625, 29)
X_test_enc: (1407, 29)

In [128]:
#Ver nombres de variables después del One-Hot
import numpy as np

ohe = preprocess.named_transformers_["cat"]
cat_features = ohe.get_feature_names_out(cat_cols)

feature_names = np.concatenate([cat_features, num_cols])
print("Total features:", len(feature_names))
print("Ejemplo:", feature_names[:15])

Total features: 29
Ejemplo: ['gender_Female' 'gender_Male' 'MultipleLines_No'
 'MultipleLines_No phone service' 'MultipleLines_Yes'
 'InternetService_DSL' 'InternetService_Fiber optic' 'InternetService_No'
 'Contract_Month-to-month' 'Contract_One year' 'Contract_Two year'
 'PaymentMethod_Bank transfer (automatic)'
 'PaymentMethod_Credit card (automatic)' 'PaymentMethod_Electronic check'
 'PaymentMethod_Mailed check']

#Verificación de la Proporción de Cancelación (Churn)

In [129]:
#Contando cuántos clientes hay en cada clase (0 y 1)
conteo = df_modelo["Churn"].value_counts()
print("Conteo por clase:\n", conteo)

Conteo por clase:
 Churn
0    5163
1    1869
Name: count, dtype: int64

In [130]:
#Calculando la proporción (porcentaje)
proporcion = df_modelo["Churn"].value_counts(normalize=True) * 100
print("\nProporción (%):\n", proporcion.round(2))

Proporción (%):
 Churn
0    73.42
1    26.58
Name: proportion, dtype: float64

In [131]:
#Interpretación rápida del desbalance
#¿Por que?
#Si una clase domina mucho (por ejemplo 90/10), los modelos pueden “aprender” a predecir siempre la clase mayoritaria y aun así tener buena accuracy.
pct_no = proporcion.loc[0]
pct_si = proporcion.loc[1]

print(f"\nClientes activos (0): {pct_no:.2f}%")
print(f"Clientes que cancelaron (1): {pct_si:.2f}%")

if pct_si < 30:
    print("\n⚠️ Hay desbalance moderado: la clase 1 (cancelación) es menor.")
    print("Recomendación: evaluar con métricas como recall, F1 y ROC-AUC (no solo accuracy).")
else:
    print("\n✅ El desbalance no es tan fuerte, pero igual conviene usar métricas adicionales.")

Clientes activos (0): 73.42%
Clientes que cancelaron (1): 26.58%

⚠️ Hay desbalance moderado: la clase 1 (cancelación) es menor.
Recomendación: evaluar con métricas como recall, F1 y ROC-AUC (no solo accuracy).

#Balanceo de Clases

In [132]:
#Preparar X/y de entrenamiento
from sklearn.model_selection import train_test_split

X = df_modelo.drop(columns=["Churn"])
y = df_modelo["Churn"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Churn train (%):")
print(y_train.value_counts(normalize=True) * 100)

Churn train (%):
Churn
0    73.422222
1    26.577778
Name: proportion, dtype: float64

In [133]:
#Codificar categóricas antes de balancear
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

cat_cols = X_train.select_dtypes(include=["object"]).columns.tolist()
num_cols = X_train.select_dtypes(exclude=["object"]).columns.tolist()

preprocess = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore", sparse_output=False), cat_cols)
    ],
    remainder="passthrough"
)

X_train_enc = preprocess.fit_transform(X_train)
X_test_enc  = preprocess.transform(X_test)

print("Shape train encoded:", X_train_enc.shape)
print("Shape test encoded:", X_test_enc.shape)

Shape train encoded: (5625, 29)
Shape test encoded: (1407, 29)

In [134]:
#Oversampling simple
#Usando la libreria imbalanced-learn
!pip -q install imbalanced-learn

In [135]:
#Oversampling
from imblearn.over_sampling import RandomOverSampler
from collections import Counter

ros = RandomOverSampler(random_state=42)
X_train_ros, y_train_ros = ros.fit_resample(X_train_enc, y_train)

print("Antes:", Counter(y_train))
print("Después (ROS):", Counter(y_train_ros))

Antes: Counter({0: 4130, 1: 1495})
Después (ROS): Counter({0: 4130, 1: 4130})

In [136]:
#Undersampling
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter

rus = RandomUnderSampler(random_state=42)
X_train_rus, y_train_rus = rus.fit_resample(X_train_enc, y_train)

print("Antes:", Counter(y_train))
print("Después (RUS):", Counter(y_train_rus))

Antes: Counter({0: 4130, 1: 1495})
Después (RUS): Counter({0: 1495, 1: 1495})

In [137]:
#EMOTE
from imblearn.over_sampling import SMOTE
from collections import Counter

smote = SMOTE(random_state=42, k_neighbors=5)
X_train_sm, y_train_sm = smote.fit_resample(X_train_enc, y_train)

print("Antes:", Counter(y_train))
print("Después (SMOTE):", Counter(y_train_sm))

Antes: Counter({0: 4130, 1: 1495})
Después (SMOTE): Counter({0: 4130, 1: 4130})

In [138]:
#Confirmando balance
print("Proporción original:", y_train.value_counts(normalize=True).round(3).to_dict())
print("Proporción ROS:", y_train_ros.value_counts(normalize=True).round(3).to_dict())
print("Proporción SMOTE:", y_train_sm.value_counts(normalize=True).round(3).to_dict())

Proporción original: {0: 0.734, 1: 0.266}
Proporción ROS: {0: 0.5, 1: 0.5}
Proporción SMOTE: {0: 0.5, 1: 0.5}

#Normalización o Estandarización